### ISSUE TITLE
Sensirion MyAmbience

### ISSUE THREAD

**Issue by nissguy** [Sensirion/SmartGadget-iOS#2] opened 2023-02-27 15:54 UTC
I couldn't find a repository for the app, so I'm posting this here. For some reason the share feature on my ipad is no longer working, but it works just fine on my iphone.

I successfully shared the data log on February 10th from the ipad, but today it does not work. I have since updated the app, updated the IOS and restarted the ipad twice. No luck.

**Comment by quentin-cy** [comment] 2023-02-28 09:50
Hello @nissguy ,
The app is not open-source, so no repository.
I am sorry you had issues with data export, could you quickly tell me your IOS version ?
I will then open a bug internally and close this issue since it is unrelated to the repo.

**Comment by nissguy** [comment] 2023-02-28 13:29
Thank you so much @qfisch for responding so quickly.

My MyAmbience Application Version is 2.5.0 (56) and my iPad IOS is 16.3.1, and its an iPad Air 5th Gen.

For correspondence when you close this bug, should I provide you with my email address?

Just some feedback, I absolutely love this app and these sensors. Would it be possible to have the option to export the data as .csv and include the absolute humidity and dew points as well?

Thanks!

**Comment by quentin-cy** [comment] 2023-02-28 14:10
Thanks for the details of your platform.
With that we should be able to reproduce and fix it.
Thank you as well for your feedback, we will consider adding more export options.
Cheers,

**Closed as completed by quentin-cy** 2023-02-28 14:10 UTC

**Comment by nissguy** [comment] 2023-02-28 14:11
Thanks Quentin, please let me know when you have a fix.

Cheers!

**Comment by nissguy** [comment] 2023-03-24 01:22
@qfisch I just wanted to follow up and see if there was a resolution to this bug?

Thanks!

**Comment by quentin-cy** [comment] 2023-03-24 06:21
Hello @nissguy ,
The bug seems solved. 
The next release should arrive in less than a month, the bugfix will be included.

**Comment by nissguy** [comment] 2023-03-24 13:25
Thanks! I appreciate it!

Niss Feiner
________________________________

**Comment by nissguy** [comment] 2023-03-28 13:29
@qfisch I'm not sure who to bring this up to. I have two older SCD4x CO2 Gadgets(device id DA:18 and E6:B0) both are updated to firmware 1.5 and I can't seem to flash them properly with the new logging interval or LED brightness.

Thanks!

**Comment by quentin-cy** [comment] 2023-03-29 07:04
Hello @nissguy,
I raised the issue internally. Is it still on your iPad ? or the issue is also present through other devices ?
Concerning the right place to report issues, there is currently non for MyAmbience. we plan to have a feedback form in the close future though.

**Comment by nissguy** [comment] 2023-03-30 16:48
Thanks @qfisch. Yes it is on my ipad that I'm having these issues.

I appreciate the response and that there will be a future form for feedback. I really like the app and the gadgets. I've been using them to log the conditions of some of my sites, and so really value the app. 

Thanks!

**Comment by LeonieFierz** [comment] 2023-04-06 12:53
@nissguy we are trying to reproduce your problem with not being able to update the logging interval or LED brightness on your SCD4x CO2 gadgets. Can you see the current values in the gadget settings? And does your SCD4x gadgets starts blinking in blue once you change and want to apply a new value? Thanks for your feedback!

**Comment by nissguy** [comment] 2023-04-06 12:58
Thanks for your response @LeonieFierz 

I tried it from my iphone and that seemed to work ok. I then tried again from my tablet and now that seems to work. I'm not sure why it works now but not then. Either way I'll take it :)

I'm still unable to share from the tablet app, but able to share from my iphone app. Looking forward to that update!

Thank you very much for your response!

**Comment by LeonieFierz** [comment] 2023-04-11 08:32
Thank you for the feedback and testing. Please let us know if you encounter any problems again.

**Comment by quentin-cy** [comment] 2023-05-02 11:14
Hej @nissguy ,

New version is out there, including the fix for your export issue.
We hope you will like the work done

Cheers
